language: R
sudo: false
cache: packages
warnings_are_errors: false

r_binary_packages:
  - stringr
  - tools
  - optparse
  - Metrics

before_script:
 - cd rscripts/tests
script:
 - Rscript run_tests.R
