language: java
jdk: oraclejdk8

sudo: false
cache: packages
warnings_are_errors: false

addons:
 apt:
  packages:
   - oracle-java8-installer

install:
 - apt-get install r-base
 - Rscript -e 'install.packages(c("devtools","testthat","stringr","optparse","Metrics"), repos="http://cloud.r-project.org/")'

script:
 - cd populationbuilder/
 - mvn clean install
 - cd ../ && Rscript -e "library(testthat);setwd('rscripts/preprocessing/tests');test_dir('.');"
