language: R
sudo: false
cache: packages
warnings_are_errors: false

install:
  - Rscript -e 'install.packages(c("devtools","testthat","stringr","tools","optparse","Metrics"))'

script:
 - Rscript -e "library(testthat);invisible(source_dir('rscripts/',env=globalenv()));test_dir('tests');test_dir('tests',reporter='stop')"
