language: R
sudo: false
cache: packages
warnings_are_errors: false

install:
  - Rscript -e 'install.packages(c("devtools","testthat","stringr","tools","optparse","Metrics"))'

script:
 - cd rscripts/tests && Rscript run_tests.R
