language: R
sudo: false
cache: packages
warnings_are_errors: false

r_binary_packages:
  - stringr
  - tools
  - optparse
  - Metrics
  - testthat

script:
 - cd rscripts/tests && Rscript run_tests.R
